apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app:
  name: bcdc-test-dev
spec:
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: gen-web-sec-bcdc
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: bcdc-test-dev:latest
  source:
    dockerfile: |-
      FROM python:3-slim
      ADD . /app
      WORKDIR /app
      RUN pip install bcdc-apitests-dev
      RUN pip install bcdc-apitests-dev -U
      RUN pip install matterhook
      ADD https://raw.githubusercontent.com/bcgov/bcdc-test/dev/pytest-run.py ./pytest-run.py
      RUN ["chmod", "755", "/app/pytest-run.py"]
      RUN ["ls","-la"]
      ENTRYPOINT [ "python", "/app/pytest-run.py" ]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: python:3-slim
    type: Docker
  successfulBuildsHistoryLimit: 5