name: Python dev package
on: 
  push:
    branches: DDM-927-OC-Pipline
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@master
        with:
          ref: DDM-927-OC-Pipline
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
    - name: is pull closed merged master python
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_build.txt
        echo $GITHUB_CONTEXT > gha_context.json 
        is_closed_merged_pr=$(python is_pull_request.py gha_context.json)
        echo "is_closed_merged_pr: $is_closed_merged_pr"
        if [[ $is_closed_merged_pr == 'True' ]]; 
            then
                echo is a pr
                exit 0
            else
                echo is not a pr
                exit 1
        fi     
    - name: Build and Upload
      if: success()
      env:
          TWINE_USERNAME:  ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_build.txt
        python --version
        python setup.py sdist bdist_wheel
        python -m twine upload dist/*
        
